// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: demo/demo.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type A struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Def *A_ADef `protobuf:"bytes,1,opt,name=def,proto3" json:"def,omitempty"`
	Abc string  `protobuf:"bytes,2,opt,name=abc,proto3" json:"abc,omitempty"`
}

func (x *A) Reset() {
	*x = A{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A) ProtoMessage() {}

func (x *A) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A.ProtoReflect.Descriptor instead.
func (*A) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *A) GetDef() *A_ADef {
	if x != nil {
		return x.Def
	}
	return nil
}

func (x *A) GetAbc() string {
	if x != nil {
		return x.Abc
	}
	return ""
}

type B struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ghi []string `protobuf:"bytes,1,rep,name=ghi,proto3" json:"ghi,omitempty"`
	Abc string   `protobuf:"bytes,2,opt,name=abc,proto3" json:"abc,omitempty"`
	Def *B_BDef  `protobuf:"bytes,3,opt,name=def,proto3" json:"def,omitempty"`
}

func (x *B) Reset() {
	*x = B{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B) ProtoMessage() {}

func (x *B) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B.ProtoReflect.Descriptor instead.
func (*B) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *B) GetGhi() []string {
	if x != nil {
		return x.Ghi
	}
	return nil
}

func (x *B) GetAbc() string {
	if x != nil {
		return x.Abc
	}
	return ""
}

func (x *B) GetDef() *B_BDef {
	if x != nil {
		return x.Def
	}
	return nil
}

type BindAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *BindAddr) Reset() {
	*x = BindAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAddr) ProtoMessage() {}

func (x *BindAddr) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAddr.ProtoReflect.Descriptor instead.
func (*BindAddr) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{2}
}

func (x *BindAddr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BindAddr) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Select:
	//	*C_BValue
	//	*C_AValue
	Select isC_Select `protobuf_oneof:"select"`
}

func (x *C) Reset() {
	*x = C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C) ProtoMessage() {}

func (x *C) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C.ProtoReflect.Descriptor instead.
func (*C) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{3}
}

func (m *C) GetSelect() isC_Select {
	if m != nil {
		return m.Select
	}
	return nil
}

func (x *C) GetBValue() *B {
	if x, ok := x.GetSelect().(*C_BValue); ok {
		return x.BValue
	}
	return nil
}

func (x *C) GetAValue() *A {
	if x, ok := x.GetSelect().(*C_AValue); ok {
		return x.AValue
	}
	return nil
}

type isC_Select interface {
	isC_Select()
}

type C_BValue struct {
	BValue *B `protobuf:"bytes,1,opt,name=BValue,proto3,oneof"`
}

type C_AValue struct {
	AValue *A `protobuf:"bytes,2,opt,name=AValue,proto3,oneof"`
}

func (*C_BValue) isC_Select() {}

func (*C_AValue) isC_Select() {}

type A_ADef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member1     string                    `protobuf:"bytes,1,opt,name=member1,proto3" json:"member1,omitempty"`
	Member2     *B                        `protobuf:"bytes,2,opt,name=member2,proto3" json:"member2,omitempty"`
	Member3     []*A_ADef_ADefMember3Elem `protobuf:"bytes,3,rep,name=member3,proto3" json:"member3,omitempty"`
	AccessPoint []*BindAddr               `protobuf:"bytes,4,rep,name=accessPoint,proto3" json:"accessPoint,omitempty"`
}

func (x *A_ADef) Reset() {
	*x = A_ADef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *A_ADef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A_ADef) ProtoMessage() {}

func (x *A_ADef) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A_ADef.ProtoReflect.Descriptor instead.
func (*A_ADef) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *A_ADef) GetMember1() string {
	if x != nil {
		return x.Member1
	}
	return ""
}

func (x *A_ADef) GetMember2() *B {
	if x != nil {
		return x.Member2
	}
	return nil
}

func (x *A_ADef) GetMember3() []*A_ADef_ADefMember3Elem {
	if x != nil {
		return x.Member3
	}
	return nil
}

func (x *A_ADef) GetAccessPoint() []*BindAddr {
	if x != nil {
		return x.AccessPoint
	}
	return nil
}

type A_ADef_ADefMember3Elem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *A_ADef_ADefMember3Elem) Reset() {
	*x = A_ADef_ADefMember3Elem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *A_ADef_ADefMember3Elem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A_ADef_ADefMember3Elem) ProtoMessage() {}

func (x *A_ADef_ADefMember3Elem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A_ADef_ADefMember3Elem.ProtoReflect.Descriptor instead.
func (*A_ADef_ADefMember3Elem) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *A_ADef_ADefMember3Elem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *A_ADef_ADefMember3Elem) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type B_BDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member1 string `protobuf:"bytes,1,opt,name=member1,proto3" json:"member1,omitempty"`
}

func (x *B_BDef) Reset() {
	*x = B_BDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_BDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_BDef) ProtoMessage() {}

func (x *B_BDef) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_BDef.ProtoReflect.Descriptor instead.
func (*B_BDef) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{1, 0}
}

func (x *B_BDef) GetMember1() string {
	if x != nil {
		return x.Member1
	}
	return ""
}

var File_demo_demo_proto protoreflect.FileDescriptor

var file_demo_demo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x22, 0xb5, 0x02, 0x0a, 0x01, 0x41,
	0x12, 0x22, 0x0a, 0x03, 0x64, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x41, 0x2e, 0x41, 0x5f, 0x64, 0x65, 0x66, 0x52,
	0x03, 0x64, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x62, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x62, 0x63, 0x1a, 0xf9, 0x01, 0x0a, 0x05, 0x41, 0x5f, 0x64, 0x65, 0x66,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x24, 0x0a, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6f,
	0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x42, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x32,
	0x12, 0x3c, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x33, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x41, 0x2e, 0x41, 0x5f,
	0x64, 0x65, 0x66, 0x2e, 0x41, 0x5f, 0x64, 0x65, 0x66, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x33, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x33, 0x12, 0x33,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x42, 0x69,
	0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x1a, 0x3d, 0x0a, 0x11, 0x41, 0x5f, 0x64, 0x65, 0x66, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x33, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x22, 0x6e, 0x0a, 0x01, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x68, 0x69, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x67, 0x68, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x62, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x62, 0x63, 0x12, 0x22, 0x0a, 0x03, 0x64,
	0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62,
	0x61, 0x72, 0x2e, 0x42, 0x2e, 0x42, 0x5f, 0x64, 0x65, 0x66, 0x52, 0x03, 0x64, 0x65, 0x66, 0x1a,
	0x21, 0x0a, 0x05, 0x42, 0x5f, 0x64, 0x65, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x31, 0x22, 0x32, 0x0a, 0x08, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x59, 0x0a, 0x01, 0x43, 0x12, 0x24, 0x0a, 0x06, 0x42,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6f,
	0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x42, 0x48, 0x00, 0x52, 0x06, 0x42, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x41, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x41, 0x48, 0x00, 0x52,
	0x06, 0x41, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_demo_demo_proto_rawDescOnce sync.Once
	file_demo_demo_proto_rawDescData = file_demo_demo_proto_rawDesc
)

func file_demo_demo_proto_rawDescGZIP() []byte {
	file_demo_demo_proto_rawDescOnce.Do(func() {
		file_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_demo_proto_rawDescData)
	})
	return file_demo_demo_proto_rawDescData
}

var file_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_demo_demo_proto_goTypes = []interface{}{
	(*A)(nil),                      // 0: foo.bar.A
	(*B)(nil),                      // 1: foo.bar.B
	(*BindAddr)(nil),               // 2: foo.bar.BindAddr
	(*C)(nil),                      // 3: foo.bar.C
	(*A_ADef)(nil),                 // 4: foo.bar.A.A_def
	(*A_ADef_ADefMember3Elem)(nil), // 5: foo.bar.A.A_def.A_def_member3Elem
	(*B_BDef)(nil),                 // 6: foo.bar.B.B_def
}
var file_demo_demo_proto_depIdxs = []int32{
	4, // 0: foo.bar.A.def:type_name -> foo.bar.A.A_def
	6, // 1: foo.bar.B.def:type_name -> foo.bar.B.B_def
	1, // 2: foo.bar.C.BValue:type_name -> foo.bar.B
	0, // 3: foo.bar.C.AValue:type_name -> foo.bar.A
	1, // 4: foo.bar.A.A_def.member2:type_name -> foo.bar.B
	5, // 5: foo.bar.A.A_def.member3:type_name -> foo.bar.A.A_def.A_def_member3Elem
	2, // 6: foo.bar.A.A_def.accessPoint:type_name -> foo.bar.BindAddr
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_demo_demo_proto_init() }
func file_demo_demo_proto_init() {
	if File_demo_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*A); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*A_ADef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*A_ADef_ADefMember3Elem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_BDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_demo_demo_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*C_BValue)(nil),
		(*C_AValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_demo_proto_goTypes,
		DependencyIndexes: file_demo_demo_proto_depIdxs,
		MessageInfos:      file_demo_demo_proto_msgTypes,
	}.Build()
	File_demo_demo_proto = out.File
	file_demo_demo_proto_rawDesc = nil
	file_demo_demo_proto_goTypes = nil
	file_demo_demo_proto_depIdxs = nil
}
