openapi: "3.0.0"
info:
  version: 1.0.0
  title: Lux API
  license:
    name: MIT
servers:
  - url: http://github.com/Axili39/lux
paths:
components:
  schemas:
    C:
      oneOf:
        - $ref: "#/components/schemas/B"
        - $ref: "#/components/schemas/C"
    BindAddr:
      type: object
      properties:
        addr:
          type: string
        port:
          type: integer
    B:
      type: object
      properties:
        abc:
          type: string
        def:
          type: object
          properties:
            member1:
              type: string
        ghi:
          type: array
          items:
            type: string
    A:
      type: object
      properties:
        abc:
          type: string
        def:
          type: object
          properties:
            member1:
              type: string
            member2:
              $ref: "#/components/schemas/B"
            member3:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  valid:
                    type: boolean
            accessPoint:
              type: array
              items:
                $ref: "#/components/schemas/BindAddr"
