// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.7.1
// source: lux/lux.proto

package lux

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TopologyStatus_TopologyStatusStatus int32

const (
	TopologyStatus_INITIALIZING TopologyStatus_TopologyStatusStatus = 0
	TopologyStatus_STOPPED      TopologyStatus_TopologyStatusStatus = 1
	TopologyStatus_STARTED      TopologyStatus_TopologyStatusStatus = 2
	TopologyStatus_ERROR        TopologyStatus_TopologyStatusStatus = 3
)

// Enum value maps for TopologyStatus_TopologyStatusStatus.
var (
	TopologyStatus_TopologyStatusStatus_name = map[int32]string{
		0: "INITIALIZING",
		1: "STOPPED",
		2: "STARTED",
		3: "ERROR",
	}
	TopologyStatus_TopologyStatusStatus_value = map[string]int32{
		"INITIALIZING": 0,
		"STOPPED":      1,
		"STARTED":      2,
		"ERROR":        3,
	}
)

func (x TopologyStatus_TopologyStatusStatus) Enum() *TopologyStatus_TopologyStatusStatus {
	p := new(TopologyStatus_TopologyStatusStatus)
	*p = x
	return p
}

func (x TopologyStatus_TopologyStatusStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopologyStatus_TopologyStatusStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lux_lux_proto_enumTypes[0].Descriptor()
}

func (TopologyStatus_TopologyStatusStatus) Type() protoreflect.EnumType {
	return &file_lux_lux_proto_enumTypes[0]
}

func (x TopologyStatus_TopologyStatusStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopologyStatus_TopologyStatusStatus.Descriptor instead.
func (TopologyStatus_TopologyStatusStatus) EnumDescriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{0, 0}
}

type TopologyStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status TopologyStatus_TopologyStatusStatus `protobuf:"varint,3,opt,name=status,proto3,enum=TopologyStatus_TopologyStatusStatus" json:"status,omitempty"`
}

func (x *TopologyStatus) Reset() {
	*x = TopologyStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyStatus) ProtoMessage() {}

func (x *TopologyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyStatus.ProtoReflect.Descriptor instead.
func (*TopologyStatus) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopologyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopologyStatus) GetStatus() TopologyStatus_TopologyStatusStatus {
	if x != nil {
		return x.Status
	}
	return TopologyStatus_INITIALIZING
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TopologyDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options  *TopologyDef_TopologyDefOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Nodes    map[string]*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Networks map[string]*Network             `protobuf:"bytes,4,rep,name=networks,proto3" json:"networks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TopologyDef) Reset() {
	*x = TopologyDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyDef) ProtoMessage() {}

func (x *TopologyDef) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyDef.ProtoReflect.Descriptor instead.
func (*TopologyDef) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{2}
}

func (x *TopologyDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopologyDef) GetOptions() *TopologyDef_TopologyDefOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TopologyDef) GetNodes() map[string]*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TopologyDef) GetNetworks() map[string]*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string                            `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Networks    map[string]*Node_NodeNetworksElem `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Node) GetNetworks() map[string]*Node_NodeNetworksElem {
	if x != nil {
		return x.Networks
	}
	return nil
}

type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipaddr  string `protobuf:"bytes,1,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Usedns  bool   `protobuf:"varint,2,opt,name=usedns,proto3" json:"usedns,omitempty"`
	Usedhcp bool   `protobuf:"varint,3,opt,name=usedhcp,proto3" json:"usedhcp,omitempty"`
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{4}
}

func (x *Network) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *Network) GetUsedns() bool {
	if x != nil {
		return x.Usedns
	}
	return false
}

func (x *Network) GetUsedhcp() bool {
	if x != nil {
		return x.Usedhcp
	}
	return false
}

type Topology struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options  *Topology_TopologyOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Nodes    map[string]*Node          `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Networks map[string]*Network       `protobuf:"bytes,4,rep,name=networks,proto3" json:"networks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id       string                    `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Topology) Reset() {
	*x = Topology{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{5}
}

func (x *Topology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topology) GetOptions() *Topology_TopologyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Topology) GetNodes() map[string]*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Topology) GetNetworks() map[string]*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *Topology) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TopologyDef_TopologyDefOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminNetworkBridge string `protobuf:"bytes,1,opt,name=adminNetworkBridge,proto3" json:"adminNetworkBridge,omitempty"`
}

func (x *TopologyDef_TopologyDefOptions) Reset() {
	*x = TopologyDef_TopologyDefOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyDef_TopologyDefOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyDef_TopologyDefOptions) ProtoMessage() {}

func (x *TopologyDef_TopologyDefOptions) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyDef_TopologyDefOptions.ProtoReflect.Descriptor instead.
func (*TopologyDef_TopologyDefOptions) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TopologyDef_TopologyDefOptions) GetAdminNetworkBridge() string {
	if x != nil {
		return x.AdminNetworkBridge
	}
	return ""
}

type Node_NodeNetworksElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dhcp    bool   `protobuf:"varint,1,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
	Mac     string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Ifname  string `protobuf:"bytes,3,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Ip4Addr string `protobuf:"bytes,4,opt,name=ip4addr,proto3" json:"ip4addr,omitempty"`
}

func (x *Node_NodeNetworksElem) Reset() {
	*x = Node_NodeNetworksElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node_NodeNetworksElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_NodeNetworksElem) ProtoMessage() {}

func (x *Node_NodeNetworksElem) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node_NodeNetworksElem.ProtoReflect.Descriptor instead.
func (*Node_NodeNetworksElem) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Node_NodeNetworksElem) GetDhcp() bool {
	if x != nil {
		return x.Dhcp
	}
	return false
}

func (x *Node_NodeNetworksElem) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Node_NodeNetworksElem) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *Node_NodeNetworksElem) GetIp4Addr() string {
	if x != nil {
		return x.Ip4Addr
	}
	return ""
}

type Topology_TopologyOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminNetworkBridge string `protobuf:"bytes,1,opt,name=adminNetworkBridge,proto3" json:"adminNetworkBridge,omitempty"`
}

func (x *Topology_TopologyOptions) Reset() {
	*x = Topology_TopologyOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lux_lux_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Topology_TopologyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology_TopologyOptions) ProtoMessage() {}

func (x *Topology_TopologyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_lux_lux_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology_TopologyOptions.ProtoReflect.Descriptor instead.
func (*Topology_TopologyOptions) Descriptor() ([]byte, []int) {
	return file_lux_lux_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Topology_TopologyOptions) GetAdminNetworkBridge() string {
	if x != nil {
		return x.AdminNetworkBridge
	}
	return ""
}

var File_lux_lux_proto protoreflect.FileDescriptor

var file_lux_lux_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x75, 0x78, 0x2f, 0x6c, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc3, 0x01, 0x0a, 0x0e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4e, 0x0a, 0x15, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x0c, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x93, 0x03, 0x0a,
	0x0b, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3a, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x65, 0x66, 0x2e,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x65, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x65, 0x66, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x65, 0x66, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x1a, 0x45, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44,
	0x65, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x1a, 0x3f, 0x0a, 0x0a, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x45, 0x0a, 0x0d, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x9c, 0x02, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a,
	0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x1a, 0x6b,
	0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45,
	0x6c, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x68, 0x63, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x68, 0x63, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x70, 0x34, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x69, 0x70, 0x34, 0x61, 0x64, 0x64, 0x72, 0x1a, 0x54, 0x0a, 0x0d, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x53, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x64, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x64, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x64, 0x68, 0x63, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75,
	0x73, 0x65, 0x64, 0x68, 0x63, 0x70, 0x22, 0x91, 0x03, 0x0a, 0x08, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x42,
	0x0a, 0x10, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x1a, 0x3f, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x45, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_lux_lux_proto_rawDescOnce sync.Once
	file_lux_lux_proto_rawDescData = file_lux_lux_proto_rawDesc
)

func file_lux_lux_proto_rawDescGZIP() []byte {
	file_lux_lux_proto_rawDescOnce.Do(func() {
		file_lux_lux_proto_rawDescData = protoimpl.X.CompressGZIP(file_lux_lux_proto_rawDescData)
	})
	return file_lux_lux_proto_rawDescData
}

var file_lux_lux_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lux_lux_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lux_lux_proto_goTypes = []interface{}{
	(TopologyStatus_TopologyStatusStatus)(0), // 0: TopologyStatus.TopologyStatus_status
	(*TopologyStatus)(nil),                   // 1: TopologyStatus
	(*Error)(nil),                            // 2: Error
	(*TopologyDef)(nil),                      // 3: TopologyDef
	(*Node)(nil),                             // 4: Node
	(*Network)(nil),                          // 5: Network
	(*Topology)(nil),                         // 6: Topology
	(*TopologyDef_TopologyDefOptions)(nil),   // 7: TopologyDef.TopologyDef_options
	nil,                                      // 8: TopologyDef.NodesEntry
	nil,                                      // 9: TopologyDef.NetworksEntry
	(*Node_NodeNetworksElem)(nil),            // 10: Node.Node_networksElem
	nil,                                      // 11: Node.NetworksEntry
	(*Topology_TopologyOptions)(nil),         // 12: Topology.Topology_options
	nil,                                      // 13: Topology.NodesEntry
	nil,                                      // 14: Topology.NetworksEntry
}
var file_lux_lux_proto_depIdxs = []int32{
	0,  // 0: TopologyStatus.status:type_name -> TopologyStatus.TopologyStatus_status
	7,  // 1: TopologyDef.options:type_name -> TopologyDef.TopologyDef_options
	8,  // 2: TopologyDef.nodes:type_name -> TopologyDef.NodesEntry
	9,  // 3: TopologyDef.networks:type_name -> TopologyDef.NetworksEntry
	11, // 4: Node.networks:type_name -> Node.NetworksEntry
	12, // 5: Topology.options:type_name -> Topology.Topology_options
	13, // 6: Topology.nodes:type_name -> Topology.NodesEntry
	14, // 7: Topology.networks:type_name -> Topology.NetworksEntry
	4,  // 8: TopologyDef.NodesEntry.value:type_name -> Node
	5,  // 9: TopologyDef.NetworksEntry.value:type_name -> Network
	10, // 10: Node.NetworksEntry.value:type_name -> Node.Node_networksElem
	4,  // 11: Topology.NodesEntry.value:type_name -> Node
	5,  // 12: Topology.NetworksEntry.value:type_name -> Network
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_lux_lux_proto_init() }
func file_lux_lux_proto_init() {
	if File_lux_lux_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lux_lux_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Topology); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyDef_TopologyDefOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node_NodeNetworksElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lux_lux_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Topology_TopologyOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lux_lux_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lux_lux_proto_goTypes,
		DependencyIndexes: file_lux_lux_proto_depIdxs,
		EnumInfos:         file_lux_lux_proto_enumTypes,
		MessageInfos:      file_lux_lux_proto_msgTypes,
	}.Build()
	File_lux_lux_proto = out.File
	file_lux_lux_proto_rawDesc = nil
	file_lux_lux_proto_goTypes = nil
	file_lux_lux_proto_depIdxs = nil
}
