openapi: 3.0.0
info:
    title: test simple
    version: 1.0.0
paths:
    /test1:
        get:
            responses:
                "200":
                    description: pet response
                    content:
                        '*/*':
                            schema:
                                type: string
