openapi: "3.0.0"
info:
  version: 1.0.0
  title: Lux API
  license:
    name: MIT
servers:
  - url: http://github.com/Axili39/lux
paths:
components:
  schemas:
    C:
      oneOf:
        - $ref: "#/components/schemas/B"
        - $ref: "#/components/schemas/A"
    Bind-Addr:
      type: object
      x-properties-order: [addr, port]
      properties:
        addr:
          type: string
        port:
          type: integer
    B:
      type: object
      x-properties-order: [ghi, abc, def]
      properties:
        abc:
          type: string
        def:
          type: object
          properties:
            member1:
              type: string
        ghi:
          type: array
          items:
            type: string
    MyTruc:
      type: array
      description: mon tableau
      items:
        type: string

    MyTruc2:
      type: array
      description: mon tableau 2
      items:
        type: object
        x-properties-order: [abc]
        properties:
          abc:
            type: string

    MyTruc3:
      type: array
      description: mon tableau 3
      items:
        $ref: "#/components/schemas/A"
    A:
      description: "Message A"
      type: object
      x-properties-order: [def, abc]
      properties:
        abc:
          type: string
        def:
          description: membre def pour bla bla
          type: object
          x-properties-order: [member1, member2, member3, access-Point]
          properties:
            member1:
              type: string
            member2:
              $ref: "#/components/schemas/B"
            member3:
              type: array
              items:
                type: object
                x-properties-order: [the-name, valid]
                properties:
                  the-name:
                    type: string
                  valid:
                    type: boolean
            access-Point:
              type: array
              items:
                $ref: "#/components/schemas/Bind-Addr"
